Direct connection pseudo slotted communication simulation tests ready

diff --git a/sg_framework/simulations/run b/sg_framework/simulations/run
--- a/sg_framework/simulations/run
+++ b/sg_framework/simulations/run
@@ -3,9 +3,17 @@
 config="SG_MULTIHOPMANUAL_001"
 
 numberofruns=$(opp_run -x "$config" | grep "Number of runs:" | sed 's/Number of runs: //')
+lastrun=$(( $numberofruns - 1 ))
+failed=0
 
-for i in $(seq 0 $(($numberofruns-1))); do
-    echo Run $i
+for i in $(seq 0 $lastrun); do
+    echo -n "Run $i/$lastrun  "
     opp_run -n ../src:.:../../inetmanet-2.0/examples:../../inetmanet-2.0/src -l ../src/sg_framework -l ../../inetmanet-2.0/src/inet omnetpp.ini -c "$config" -u Cmdenv -G -r $i &> /dev/null
+    if [ $? -ne 0 ]; then
+        echo "Failed"
+        failed=$(( failed + 1 ))
+    else
+        echo "Ok"
+    fi
 done
-
+echo "$failed of $numberofruns runs failed"
